<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>DiffBeacon</AssemblyName>
    <PublishAot>true</PublishAot>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RuntimeIdentifiers>win-x64;win-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DiffBeacon.Core/DiffBeacon.Core.csproj" />
    <ProjectReference Include="../DiffBeacon.Providers/DiffBeacon.Providers.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.3" />
    <EmbeddedResource Include="../../tests/Fixtures/Archives/Zip.deflate.WinzipAES.zip" LogicalName="DiffBeacon.SelfTest.Encrypted.zip" />
    <EmbeddedResource Include="../../tests/Fixtures/Images/same-first-left.gif" LogicalName="DiffBeacon.SelfTest.Images.same-first-left.gif" />
    <EmbeddedResource Include="../../tests/Fixtures/Images/same-first-right.gif" LogicalName="DiffBeacon.SelfTest.Images.same-first-right.gif" />
    <EmbeddedResource Include="../../tests/Fixtures/Images/short.gif" LogicalName="DiffBeacon.SelfTest.Images.short.gif" />
    <EmbeddedResource Include="../../tests/Fixtures/Images/disposal.gif" LogicalName="DiffBeacon.SelfTest.Images.disposal.gif" />
    <EmbeddedResource Include="../../tests/Fixtures/Images/disposal-2.png" LogicalName="DiffBeacon.SelfTest.Images.disposal-2.png" />
  </ItemGroup>
</Project>
